### ISSUE TITLE
add filename as argument for read_forecast

### ISSUE THREAD

**Issue by btupper** [BigelowLab/pspforecast#1]
Allow user to specify the filename here... 

https://github.com/BigelowLab/pspforecast/blob/master/R/forecast_io.R#L28

... with default being the system file.  Maybe...

```
read_forecast <- function(
  file = system.file("forecastdb/psp_forecast_2022.csv.gz", package="pspforecast")
  format = FALSE, 
  new_only=FALSE) {
  .
  .
  .
```

**Comment by jevanilla** [comment]
read_forecast() now has file argument, but must be passed in as a variable, not the direct url.
default forecast db is still file installed with package locally.

for example, read_forecast(file="https://github.com/BigelowLab/pspforecast/blob/master/inst/forecastdb/psp_forecast_2022.csv.gz")
won't work.

instead, use:

filename = "https://github.com/BigelowLab/pspforecast/blob/master/inst/forecastdb/psp_forecast_2022.csv.gz"
read_forecast(file=filename)
